CREATE TABLE books (
    id BIGSERIAL PRIMARY KEY,
    title VARCHAR(128) NOT NULL,
    author_name VARCHAR(64) NOT NULL,
    description VARCHAR(256),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);